[book]
authors = ["Goblin Oats", "grjte"]
language = "en"
multilingual = false
src = "src"
title = "Knot Group Wiki"
description = "Wiki on programmable cryptography over advanced decentralisation technologies for novel, emergent applications. "

[build]
create-missing = false